// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH134qCFQIxC9_8FBcGZYvPVDwTsYg2Lo',
    appId: '1:481691584658:web:6794c9a2ad60212df43e4b',
    messagingSenderId: '481691584658',
    projectId: 'english-b1-app',
    authDomain: 'english-b1-app.firebaseapp.com',
    storageBucket: 'english-b1-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN154HnvxzVHDGyMEggWKBZxyHCQpTMEs',
    appId: '1:481691584658:android:97ad9141d3e0c207f43e4b',
    messagingSenderId: '481691584658',
    projectId: 'english-b1-app',
    storageBucket: 'english-b1-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqPY1vDhcLFGhbTaZT6A2KZpbTE9MlfxQ',
    appId: '1:481691584658:ios:1483895afe895d0bf43e4b',
    messagingSenderId: '481691584658',
    projectId: 'english-b1-app',
    storageBucket: 'english-b1-app.firebasestorage.app',
    iosBundleId: 'com.example.neobez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqPY1vDhcLFGhbTaZT6A2KZpbTE9MlfxQ',
    appId: '1:481691584658:ios:1483895afe895d0bf43e4b',
    messagingSenderId: '481691584658',
    projectId: 'english-b1-app',
    storageBucket: 'english-b1-app.firebasestorage.app',
    iosBundleId: 'com.example.neobez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH134qCFQIxC9_8FBcGZYvPVDwTsYg2Lo',
    appId: '1:481691584658:web:3e5f77b355ab5203f43e4b',
    messagingSenderId: '481691584658',
    projectId: 'english-b1-app',
    authDomain: 'english-b1-app.firebaseapp.com',
    storageBucket: 'english-b1-app.firebasestorage.app',
  );

}